export OPENAI_API_VERSION=2023-07-15-preview
export OPENAI_API_TYPE=AZURE
export AZURE_SEARCH_SERVICE_ENDPOINT=https://gptdocument.search.windows.net
export AZURE_SEARCH_INDEX_NAME=gptdocument
export ADMIN_KEY=W7XVOLsbEZgcvWqLD0MxpdVbAfWf1ZIZG7HYdIVSgPAzSeDTMtqR
export OPENAI_API_BASE=https://sean-aoai-gpt4.openai.azure.com/
export OPENAI_API_KEY=3397748fcdcb4a5fbeb6c2eb5a6a284f